### ISSUE TITLE
Persisting jwt information to database?

### ISSUE THREAD

**Issue by vangalamaheshh** [NovemberOscar/Flask-GraphQL-Auth#12]
Hello @NovemberOscar ,

This has been a smooth ride doing auth with graphql with this pip.
However, when the flask application restarts, the jwt will no longer be valid.
Is there a way to persist this data into a database? 
Let me know.

Thanks,
Mahesh

**Comment by NovemberOscar** [comment]
Hi! Thanks for using Flask-GraphQL-Auth :)

I think your application changes the secret key every time you restart it. 
JWT is valid even after restarting the application if the secret key is not changed.

Sincerely,
Lewis
