### ISSUE TITLE
How are the ACCESS_EXP_LENGTH and REFRESH_EXP_LENGTH values used?

### ISSUE THREAD

**Issue by grahambeckley** [NovemberOscar/Flask-GraphQL-Auth#13]
The docs reference `ACCESS_EXP_LENGTH` and `REFRESH_EXP_LENGTH` app config variables, but the only place I can find a reference to them is in the [examples and conftest.py](https://github.com/NovemberOscar/Flask-GraphQL-Auth/search?q=ACCESS_EXP_LENGTH&unscoped_q=ACCESS_EXP_LENGTH). Are these used by a dependency? Or should we use the `JWT_ACCESS_TOKEN_EXPIRES` and `JWT_REFRESH_TOKEN_EXPIRES` instead?

**Comment by NovemberOscar** [comment]
Thanks for issue!

That's my bad. We use `JWT_ACCESS_TOKEN_EXPIRES` and `JWT_REFRESH_TOKEN_EXPIRES `, not `ACCESS_EXP_LENGTH` and `REFRESH_EXP_LENGTH`. Could you open PR to update examples and conftest?
