### ISSUE TITLE
A request please

### ISSUE THREAD

**Issue by gj1118** [NovemberOscar/Flask-GraphQL-Auth#15]
Can you please create a video ( a tutorial)  describing how a layman like me can implement it ?  The reason I am asking is - I tried to follow the doc but I was not sure , I was understanding why I was doing, what I was doing. 

I hope you will take this into consideration. 

Thanks a lot for everything.

**Comment by NovemberOscar** [comment]
Thanks for idea. but unfortunately I do not have any plan on it now. but I'll consider improve the docs
