### ISSUE TITLE
Problem with array queries

### ISSUE THREAD

**Issue by alex2201** [NovemberOscar/Flask-GraphQL-Auth#17]
I had a problem while wrapping the following query with @query_jwt_required.

```
query{
  returnArrayQuery(token: ""){
    ...
}
```

The error was cause GraphQl expects an iterable and the wrapper provides AuthInfoField when theres an error with jwt. I managed to solve it with the following code.

```
def query_jwt_required_list(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        token = kwargs.pop(current_app.config["JWT_TOKEN_ARGUMENT_NAME"])
        try:
            verify_jwt_in_argument(token)
        except Exception as e:
            return [AuthInfoField(message=str(e))] # Returns a list

        return fn(*args, **kwargs)

    return wrapper
```

I wonder if there's a native solution without need to modify the source code.

**Comment by NovemberOscar** [comment]
I guess Union could solve this.
```
type MyArray {
  results: [Foo]
}

union Result = MyArray | AuthInfoField

type Query {
  returnArrayQUery(token: String): Result
}
```

https://github.com/graphql-python/graphene/issues/835
