### ISSUE TITLE
Breaking changes introduced with PyJWT V2.0.0

### ISSUE THREAD

**Issue by KrishyV** [NovemberOscar/Flask-GraphQL-Auth#23]
Creating the JWT tokens would throw `graphql.error.located_error.GraphQLLocatedError: 'str' object has no attribute 'decode'
`
The short-term solution I have is to specify your PyJWT version to be `PyJWT==1.7.1` in your requirements.txt. 

The change log can be found below.

https://github.com/jpadilla/pyjwt/releases/tag/2.0.0

**Comment by NovemberOscar** [comment]
Just approved #27. this issue will be resolved by next release. until then, downgrading pyjwt version could be a solution 🙏

and merge this issue to #25
